[package]
name = "spartan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
crypto-primitives = { workspace = true }
circuit = { path = "../circuit" }
field = { path = "../field", features = ["spongefish"] }
num-bigint.workspace = true
num-traits.workspace = true
poly = { path = "../poly" }
rayon = { workspace = true }
sha2 = "0.10"
transcript = { path = "../transcript" }

[dev-dependencies]
field = { path = "../field", features = ["rand"] }
rand = "0.9"
rand_pcg = "0.9"
