[package]
name = "spartan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
circuit = { workspace = true }
common = { workspace = true }
field = { workspace = true, features = ["spongefish"] }
poly = { workspace = true }
transcript = { workspace = true }

crypto-primitives = { workspace = true }
num-bigint.workspace = true
num-traits.workspace = true
rayon = { workspace = true }
sha2 = "0.10"
tracing = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
field = { path = "../field", features = ["rand"] }
rand = "0.9"
rand_pcg = "0.9"

[[bench]]
name = "sha256"
harness = false
