[package]
name = "poly"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[dependencies]
crypto-primitives = { workspace = true }
field = { workspace = true }
num-traits = { workspace = true }
rayon = { workspace = true, optional = true }

[dev-dependencies]
divan = { workspace = true }
proptest = { workspace = true }

[[bench]]
name = "poly"
harness = false
