[package]
name = "poly"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[dependencies]
field = { path = "../field" }
rayon = { workspace = true, optional = true }

[dev-dependencies]
divan = "0.1.21"
proptest = "1.11.0"

[[bench]]
name = "poly"
harness = false
