[package]
name = "tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
common = { workspace = true }
crypto-primitives = { workspace = true }
field = { workspace = true, features = ["spongefish"] }
host = { workspace = true }
pcs = { workspace = true }
prover = { workspace = true }
rand_chacha = { workspace = true }
rand_core = { workspace = true }
transcript = { workspace = true }
verifier = { workspace = true }

[dev-dependencies]
circuit = { workspace = true }
num-traits = { workspace = true }
