[package]
name = "pcs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bincode = { workspace = true }
blake3 = { workspace = true }
common = { workspace = true }
field = { path = "../field", features = ["spongefish"] }
flock-core = { workspace = true }
transcript = { path = "../transcript" }

[dev-dependencies]
proptest = { workspace = true }
