[package]
name = "pcs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bincode = { workspace = true }
blake3 = { workspace = true }
common = { workspace = true }
field = { workspace = true, features = ["spongefish"] }
flock-core = { workspace = true }
transcript = { workspace = true }
tracing = { workspace = true }
num-traits = { workspace = true }
poly = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
proptest = { workspace = true }

[[bench]]
name = "tensor_algebra_transpose"
harness = false
