[package]
name = "pcs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bincode = "1.3"
blake3 = "1.8"
field = { path = "../field", features = ["spongefish"] }
flock-core = { workspace = true }
transcript = { path = "../transcript" }
