//! Responsible for serializing and deserializing proofs that cross the host
//! boundary as a byte string.
//!
//! Deserialization is aware that the bytes might be generated by malicious prover,
//! so it ensures the following properties hold.
//!
//! - **No panic on hostile bytes.** Every length is checked, every
//!   conversion is fallible, no allocation is sized from an unvalidated
//!   field.
//! - **Bijection**. Each proof has exactly one encoding, and each byte
//!   string corresponds to no more than one proof.
//!
//! Note that the proof data is treated as black box and isn't validated, that's up to verifier.

mod reader;
pub mod wire_proof;

/// Property tests over hostile and well-formed input.
#[cfg(test)]
mod tests {
    use crate::wire_proof::{self, WireProof};
    use proptest::prelude::*;
    use transcript::Proof;

    /// Make a well-structured header with the given fields.
    fn header_with(lengths: (u64, u64)) -> Vec<u8> {
        let mut header = Vec::new();
        header.extend_from_slice(&wire_proof::MAGIC);
        header.extend_from_slice(&wire_proof::WIRE_VERSION.to_le_bytes());
        header.extend_from_slice(&(wire_proof::HEADER_LEN as u16).to_le_bytes());
        header.extend_from_slice(&wire_proof::FLAGS.to_le_bytes());
        header.extend_from_slice(&lengths.0.to_le_bytes());
        header.extend_from_slice(&lengths.1.to_le_bytes());
        header
    }

    /// Make sure deserializing bytes doesn't panic, and if it succeeds,
    /// it serialized back to the same exact bytes.
    fn is_well_behaved(bytes: &[u8]) -> Result<(), TestCaseError> {
        if let Ok(proof) = wire_proof::decode(bytes) {
            prop_assert_eq!(
                wire_proof::encode(&proof),
                bytes,
                "an accepted container must have exactly one spelling"
            );
        }
        Ok(())
    }

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(512))]

        #[test]
        fn arbitrary_bytes_never_panic(bytes in prop::collection::vec(any::<u8>(), 0..600)) {
            is_well_behaved(&bytes)?;
        }

        // Declared lengths are sampled across the whole `u64` range to check for wraps,
        // truncations and oversized allocations.
        #[test]
        fn a_header_with_adversarial_lengths_never_panics(
            lengths in any::<(u64, u64)>(),
            body in prop::collection::vec(any::<u8>(), 0..256),
        ) {
            let mut bytes = header_with(lengths);
            bytes.extend_from_slice(&body);
            is_well_behaved(&bytes)?;
        }

        /// The happy path roundtrip.
        #[test]
        fn a_well_formed_container_round_trips(
            narg in prop::collection::vec(any::<u8>(), 0..64),
            hints in prop::collection::vec(any::<u8>(), 0..64),
        ) {
            let mut bytes = header_with((narg.len() as u64, hints.len() as u64));
            bytes.extend_from_slice(&narg);
            bytes.extend_from_slice(&hints);

            let wire = WireProof::from_bytes(&bytes).expect("a well-formed container");
            prop_assert_eq!(wire.narg_string, &narg[..]);
            prop_assert_eq!(wire.hints, &hints[..]);
            prop_assert_eq!(wire.to_bytes(), bytes.clone());
            prop_assert_eq!(wire_proof::encode(&wire.unwrap()), bytes);
        }

        /// A valid proof rewritten in several places, then cut short and
        /// extended.
        ///
        /// Combining the three keeps the search from stopping at the first
        /// gate: a rewrite that lands in the length fields still has to
        /// survive a body that is no longer the length either field claims.
        #[test]
        fn a_mutated_proof_is_handled(
            edits in prop::collection::vec((any::<prop::sample::Index>(), any::<u8>()), 0..8),
            truncate_to in 0usize..200,
            extra in prop::collection::vec(any::<u8>(), 0..8),
        ) {
            let proof = Proof {
                narg_string: vec![7; 96],
                hints: vec![9; 32],
            };
            let mut bytes = wire_proof::encode(&proof);
            for (at, value) in edits {
                let at = at.index(bytes.len());
                bytes[at] = value;
            }
            bytes.truncate(truncate_to);
            bytes.extend_from_slice(&extra);
            is_well_behaved(&bytes)?;
        }
    }
}
