[package]
name = "common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[dependencies]
crypto-primitives = { workspace = true }
field = { workspace = true, features = ["spongefish"] }
spongefish = { workspace = true }
poly = { workspace = true }
rayon = { workspace = true, optional = true }
num-traits = { workspace = true }
