[package]
name = "common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
crypto-primitives = { workspace = true }
field = { workspace = true, features = ["spongefish"] }
spongefish = { workspace = true }
poly = { workspace = true }

[dev-dependencies]
num-traits = { workspace = true }
