[package]
name = "field"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
num-traits = { workspace = true }
crypto-primitives = { workspace = true }
crypto-primitives-proc-macros = { workspace = true }
spongefish = { workspace = true, optional = true }

[features]
spongefish = ["dep:spongefish"]

[dev-dependencies]
aes = { workspace = true }
binius-field = { workspace = true }
divan = { workspace = true }
flock-core = { workspace = true }
rand_core = { workspace = true }
rand_pcg = { workspace = true }

[[bench]]
name = "gf128"
harness = false

[[bench]]
name = "binius64"
harness = false
